// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BrickApi.Client.Api.Colours
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ColoursGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The colours property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BrickApi.Client.Api.Colours.ColoursGetResponse_colours>? Colours { get; set; }
#nullable restore
#else
        public List<global::BrickApi.Client.Api.Colours.ColoursGetResponse_colours> Colours { get; set; }
#endif
        /// <summary>The disclaimer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Disclaimer { get; set; }
#nullable restore
#else
        public string Disclaimer { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::BrickApi.Client.Api.Colours.ColoursGetResponse"/> and sets the default values.
        /// </summary>
        public ColoursGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BrickApi.Client.Api.Colours.ColoursGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BrickApi.Client.Api.Colours.ColoursGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BrickApi.Client.Api.Colours.ColoursGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "colours", n => { Colours = n.GetCollectionOfObjectValues<global::BrickApi.Client.Api.Colours.ColoursGetResponse_colours>(global::BrickApi.Client.Api.Colours.ColoursGetResponse_colours.CreateFromDiscriminatorValue)?.AsList(); } },
                { "disclaimer", n => { Disclaimer = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::BrickApi.Client.Api.Colours.ColoursGetResponse_colours>("colours", Colours);
            writer.WriteStringValue("disclaimer", Disclaimer);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
