// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace BrickApi.Client.Api.Set.ById.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public partial class ByIdGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The pieces property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse_pieces>? Pieces { get; set; }
#nullable restore
#else
        public List<global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse_pieces> Pieces { get; set; }
#endif
        /// <summary>The setNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SetNumber { get; set; }
#nullable restore
#else
        public string SetNumber { get; set; }
#endif
        /// <summary>The totalPieces property</summary>
        public double? TotalPieces { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse"/> and sets the default values.
        /// </summary>
        public ByIdGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pieces", n => { Pieces = n.GetCollectionOfObjectValues<global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse_pieces>(global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse_pieces.CreateFromDiscriminatorValue)?.AsList(); } },
                { "setNumber", n => { SetNumber = n.GetStringValue(); } },
                { "totalPieces", n => { TotalPieces = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::BrickApi.Client.Api.Set.ById.Item.ByIdGetResponse_pieces>("pieces", Pieces);
            writer.WriteStringValue("setNumber", SetNumber);
            writer.WriteDoubleValue("totalPieces", TotalPieces);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
